#  Import the numpy package under the name np 

In [6]:
import numpy as np

# Print the numpy version and the configuration 


In [7]:
np.__version__

'1.19.2'

In [36]:
print(np.__version__)
np.__config__.show()

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/saisi/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/saisi/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/saisi/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/saisi/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/saisi/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/saisi/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/saisi/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/saisi/anaconda3\\Library\\include']


# Create a null vector of size 20 

In [8]:
np.zeros(20)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

# How to find the memory size of any array 

In [9]:
x=np.random.randint(1,50,(4,4))
print(x)
print(x.itemsize)
print(x.size)

[[42  2 48 30]
 [22 32 40  1]
 [11 23 18  1]
 [ 2 38 27 10]]
4
16


# How to get the documentation of the numpy add function from the command line? 

In [39]:
import numpy
numpy.info(numpy.add)


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [13]:
import numpy 
numpy.info(numpy.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

# Create a null vector of size 20 but the fifth value which is 1 

In [11]:
x=np.zeros(20)
x[3+1]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [12]:
np.zeros(35)
x[3+1]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

# Create a vector with values ranging from 10 to 68 

In [13]:
np.random.randint(10,68)
np.arange(10,68)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67])

In [40]:
np.arange(10,68)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67])

In [14]:
s=np.arange(10,68)
print("normal array:")
print(s)

normal array:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67]


# Reverse a vector (first element becomes last) 

In [15]:
x=np.arange(10,68)
print("Reverse array:")
x=x[::-1]
print(x)



Reverse array:
[67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52 51 50 49 48 47 46 45 44
 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20
 19 18 17 16 15 14 13 12 11 10]


In [44]:
np.arange(68,0,-1)

array([68, 67, 66, 65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52,
       51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35,
       34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18,
       17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

# Create a 3x3 matrix with values ranging from 0 to 10

In [16]:
np.random.randint(0,10,(3,3))

array([[0, 7, 2],
       [4, 6, 8],
       [7, 0, 4]])

In [17]:
a=np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Find indices of non-zero elements from [0,2,1,0,4,0] 

In [18]:
sra=np.nonzero([0,2,1,0,4,0])
print(sra)

(array([1, 2, 4], dtype=int64),)


# Create a 3x3 identity matrix 

In [19]:
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Create a 3x3x3 array with random values


In [21]:
np.random.randint(1,10,(3,3,3))

array([[[3, 8, 5],
        [6, 4, 7],
        [6, 9, 6]],

       [[6, 2, 8],
        [3, 7, 7],
        [3, 4, 1]],

       [[7, 1, 1],
        [4, 4, 3],
        [9, 6, 8]]])

In [47]:
np.random.uniform((3,3,3))

array([1.96133748, 2.40116739, 2.37797587])

#  Create a 10x10 array with random values and find the minimum and maximum values 

In [23]:
np.random.randint(0,10,(10,10))

array([[5, 6, 5, 5, 2, 8, 3, 6, 8, 8],
       [0, 1, 6, 9, 9, 7, 9, 2, 4, 5],
       [8, 3, 8, 7, 7, 4, 6, 4, 4, 1],
       [0, 8, 0, 7, 5, 6, 2, 2, 5, 0],
       [8, 9, 9, 7, 3, 0, 9, 1, 9, 4],
       [1, 4, 4, 2, 0, 2, 3, 0, 2, 8],
       [6, 2, 8, 5, 5, 6, 0, 0, 7, 7],
       [2, 9, 6, 6, 7, 1, 4, 2, 7, 5],
       [8, 4, 9, 6, 8, 0, 7, 6, 1, 1],
       [7, 6, 3, 5, 8, 5, 0, 8, 7, 6]])

In [24]:
max=x.max()
min=x.min()
print(max, min)

9 0


In [26]:
s=np.random.randint(90,size=(10,10))
s

array([[37, 14, 53, 19, 59, 12, 74, 83,  8, 53],
       [38, 43, 89,  4, 36, 67, 67, 68, 51,  5],
       [85, 86, 67, 89, 60, 63, 28, 35, 39, 25],
       [62, 24, 80, 45, 54,  6, 73,  1, 77, 49],
       [83, 31, 22, 85, 61, 38, 68, 41, 66, 82],
       [10, 77, 28, 26, 29, 43, 88, 51,  1, 29],
       [18, 61, 76, 23, 75, 45, 43, 86, 33, 12],
       [ 7, 76, 26, 32, 57, 57, 59, 66, 66, 62],
       [77, 17, 31,  4,  8, 67, 15, 44, 40, 63],
       [49, 12, 51, 33, 49,  4, 25, 32, 52,  3]])

In [27]:
print(np.min(s))
print(np.max(s))

1
89


# 14. Create a random vector of size 30 and find the mean value 

In [29]:
s=np.random.randint(0,50,size=(30))
s

array([24, 10, 29, 47, 31,  6, 41, 40, 39, 11, 16, 29, 17, 27, 12, 13, 20,
       30, 31, 44, 27,  4, 18, 25,  7, 48, 20, 16,  2, 37])

In [30]:
print(np.min(s))

2


In [31]:
np.random.randint(0,10,30).mean()

4.166666666666667

In [33]:
s=np.random.randint(0,10,30)
s

array([5, 6, 9, 4, 8, 8, 0, 3, 2, 3, 1, 1, 3, 8, 4, 2, 0, 5, 8, 2, 3, 4,
       2, 7, 4, 0, 4, 3, 0, 5])

In [34]:
np.random.randint(0,10,30).mean()


5.6

In [ ]:
Z = np.random.random(10)
m = Z.mean()
print (m)


# Create a 2d array with 1 on the border and 0 inside 


In [2]:
import numpy as np
s=np.ones((5,5))
print(" 1 on the border and 0 inside in the array")
s[1:-1,1:-1]=0
print(s)

 1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# How to add a border (filled with 0's) around an existing array? 

In [14]:
import numpy as np
s=([[1,2,3,],
    [4,5,6,],
    [7,8,9,]])
border_width=1
padded_s=np.pad(s,pad_width=border_width,mode='constant',constant_values=0)
print(padded_s)

[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


# What is the result of the following expression? 

In [17]:
0 * np.nan

nan

In [18]:
np.nan == np.nan

False

In [19]:
np.inf > np.nan

False

In [20]:
np.nan - np.nan


nan

In [21]:
np.nan in set([np.nan])

True

In [22]:
0.3 == 3 * 0.1

False

# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal 

In [43]:
import numpy as np
matrix=np.zeros((5, 5), dtype=int)
for i in range(1, 5):
    matrix[i, i-1] = 1
    matrix[i-1, i] = i+1
print(matrix)    

[[0 2 0 0 0]
 [1 0 3 0 0]
 [0 1 0 4 0]
 [0 0 1 0 5]
 [0 0 0 1 0]]


In [48]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# Create a 8x8 matrix and fill it with a checkerboard pattern 


In [74]:
import numpy as np
s=np.zeros((8,8), dtype=int)
for i in range(0,8):
    for j in range(0,8):
        if(i+j)%2==0:
            s[i][j]=1
            
print(s)            
        

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# Create a checkerboard 8x8 matrix using the tile function 


In [85]:
sanjana=np.array([[0,1],[1,0]])
np.tile(sanjana,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

# Normalize a 5x5 random matrix 

In [96]:
import numpy as np
s=np.random.rand(5,5)
print("original array:")
print(s)

original array:
[[0.84386253 0.88229626 0.12866424 0.66334064 0.86041995]
 [0.10015658 0.59696172 0.29580048 0.75516973 0.77204744]
 [0.22846273 0.27111451 0.83009298 0.65728611 0.0182471 ]
 [0.01033824 0.90799405 0.70341607 0.2651647  0.27602298]
 [0.35973529 0.26448819 0.65204431 0.9717544  0.38963373]]


In [97]:
import numpy as np
s=np.random.rand(5,5)
print("original array")
print(s)
xmax,xmin=x.max(),x.min()
s=(x-xmin)/(xmax-xmin)
print("after normalization")
print(s)

original array
[[0.59939931 0.81522075 0.90505855 0.71480405 0.19188818]
 [0.32720079 0.18756079 0.77091189 0.1745169  0.52175801]
 [0.10657929 0.76663537 0.90373633 0.96767677 0.22020072]
 [0.1535377  0.43188135 0.47084483 0.50326825 0.99356893]
 [0.99782155 0.0563693  0.84709625 0.5876908  0.0644463 ]]
after normalization
[[0.34576235 0.4527872  0.6714035  0.45243407 0.93289545]
 [0.68677551 0.19040617 1.         0.59201737 0.49130824]
 [0.9082682  0.43337997 0.84041306 0.30175482 0.41680473]
 [0.31814299 0.09682604 0.75284262 0.64452475 0.0566087 ]
 [0.33270002 0.51486683 0.         0.89856061 0.94277301]]


In [98]:
import numpy as np
s=np.random.rand(5,5)
xmax,xmin=x.max(),x.min()
s=(x-xmin)/(xmax-xmin)
print("normalization")
print(s)

normalization
[[0.34576235 0.4527872  0.6714035  0.45243407 0.93289545]
 [0.68677551 0.19040617 1.         0.59201737 0.49130824]
 [0.9082682  0.43337997 0.84041306 0.30175482 0.41680473]
 [0.31814299 0.09682604 0.75284262 0.64452475 0.0566087 ]
 [0.33270002 0.51486683 0.         0.89856061 0.94277301]]


In [99]:
import numpy as np
s=np.random.rand(5,5)
s=(x-xmin)/(xmax-xmin)
print("normalization")
print(s)

normalization
[[0.34576235 0.4527872  0.6714035  0.45243407 0.93289545]
 [0.68677551 0.19040617 1.         0.59201737 0.49130824]
 [0.9082682  0.43337997 0.84041306 0.30175482 0.41680473]
 [0.31814299 0.09682604 0.75284262 0.64452475 0.0566087 ]
 [0.33270002 0.51486683 0.         0.89856061 0.94277301]]


# Create a custom dtype that describes a color as four unsigned bytes (RGBA) 

In [106]:
import numpy as np


In [107]:
color_dtype = np.dtype([('r', np.uint8), ('g', np.uint8), ('b', np.uint8), ('a', np.uint8)])



In [108]:
colors = np.array([(255, 0, 0, 255), (0, 255, 0, 255), (0, 0, 255, 255)], dtype=color_dtype)


In [109]:
print(colors[0]['r'])

255


In [110]:
print(colors[0]['g'])

0


In [111]:
print(colors[0]['b'])

0


In [112]:
print(colors[0]['a'])

255


# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) 

In [121]:
s=np.random.randint(0,10,(5,3))
a=np.random.randint(0,10,(3,2))

In [122]:
s

array([[7, 2, 4],
       [1, 2, 7],
       [4, 1, 0],
       [7, 2, 6],
       [7, 4, 3]])

In [123]:
a

array([[1, 4],
       [7, 8],
       [1, 8]])

In [124]:
data=np.random.randint(10,20,(5,3))


In [125]:
data

array([[11, 19, 16],
       [17, 13, 12],
       [10, 16, 14],
       [16, 13, 12],
       [10, 19, 18]])

In [126]:
sa=np.random.randint(50,60,(3,2))

In [127]:
sa

array([[57, 55],
       [54, 59],
       [58, 51]])

# Given a 1D array, negate all elements which are between 3 and 8, in place. 

In [131]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])

In [132]:
a[(a >= 3) & (a <= 8)] *= -1



In [134]:
print(a)

[ 1  2 -3 -4 -5 -6 -7 -8  9 10 11 12 13 14 15]


# What is the output of the following script? 

In [364]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


# What are the result of the following expressions? 


In [151]:
np.array(0) / np.array(0)

<ipython-input-151-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


nan

In [152]:
np.array(0) / np.array(0)

<ipython-input-152-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


nan

In [153]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

# How to find common values between two arrays? 


In [165]:
s=np.random.randint(0,10,(2,2))

In [166]:
a=np.random.randint(0,10,(2,2))

In [168]:
print(s)
print(a)
x=np.intersect1d(s,a)
x

[[0 9]
 [7 6]]
[[4 4]
 [7 1]]


array([7])

In [170]:
sa=np.array([1,2,3,4,5,6,7])
p=np.array([5,6,3,9,7,5,1])

In [174]:
common_value=np.intersect1d(sa,p)

In [176]:
print(common_value)

[1 3 5 6 7]


# How to ignore all numpy warnings (not recommended)? 

In [177]:
import numpy as np
import warnings

In [178]:
warnings.filterwarnings("ignore")

In [179]:
warnings.filterwarnings("default")

# Is the following expressions true? 


In [180]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\saisi\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
<ipython-input-180-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

# How to get the dates of yesterday, today and tomorrow? 

In [236]:
import numpy as np
import pandas as pd
import datetime


In [237]:
today=datetime.date.today()
yesterday=today-datetime.timedelta(days=1)
tomorrow=today+datetime.timedelta(days=1)
print("Yesterday:",yesterday)
print("Today is:",today)
print("Tomorrow will be:",tomorrow)

Yesterday: 2023-03-01
Today is: 2023-03-02
Tomorrow will be: 2023-03-03


C:\Users\saisi\anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


# How to get all the dates corresponding to the month of July 2016? 


In [239]:
import calendar
import numpy as np
year=2016
month=7
num_days=calendar.monthrange(year,month)[1]
dates=[datetime.date(year,month,day) for day in range(1,num_days+1)]
for date in dates:
    print(date)
    

2016-07-01
2016-07-02
2016-07-03
2016-07-04
2016-07-05
2016-07-06
2016-07-07
2016-07-08
2016-07-09
2016-07-10
2016-07-11
2016-07-12
2016-07-13
2016-07-14
2016-07-15
2016-07-16
2016-07-17
2016-07-18
2016-07-19
2016-07-20
2016-07-21
2016-07-22
2016-07-23
2016-07-24
2016-07-25
2016-07-26
2016-07-27
2016-07-28
2016-07-29
2016-07-30
2016-07-31


# Extract the integer part of a random array of positive numbers using 4 different methods 

In [241]:
import numpy as np
sra=np.random.randint(5)*10
int_sra = sra // 1
print(int_sra)

40


In [ ]:
Using numpy's floor function

In [245]:
import numpy as np
san=np.random.rand(9)*10
int_san = np.floor(san)
print(int_san)

[3. 3. 1. 1. 2. 4. 4. 7. 8.]


In [ ]:
Using numpy's trunc function

In [244]:
import numpy as np
data=np.random.rand(4)*10
int_data = np.trunc(data)
print(int_data)


[3. 5. 4. 1.]


In [ ]:
Using type casting to integer


In [246]:
import numpy as np
s=np.random.rand(8)*20
int_s = s.astype(int)
print(int_s)

[14  5 10 13 19  3  0 11]


# Create a 5x5 matrix with row values ranging from 0 to 5 


In [250]:
np.random.randint(0,6,(5,5))


array([[1, 2, 4, 0, 3],
       [4, 0, 4, 5, 1],
       [2, 2, 4, 1, 4],
       [1, 3, 3, 0, 4],
       [2, 3, 2, 0, 4]])

# Create a vector of size 10 with values ranging from 0 to 1, both excluded 


In [253]:
np.random.rand(10)

array([0.12608423, 0.14303916, 0.45593182, 0.12323021, 0.58554191,
       0.82213111, 0.93994246, 0.29546329, 0.56361758, 0.41237954])

In [ ]:
in the linspace function to create an array of 12 values ranging from 0 to 1

In [255]:
san = np.linspace(0, 1, num=12, endpoint=True)[1:-1]

In [256]:
print(san)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


# Create a random vector of size 20 and sort it 


In [259]:
s=np.random.randint(0,10,20)
s

array([9, 3, 4, 1, 9, 1, 2, 1, 3, 3, 0, 7, 6, 8, 7, 1, 9, 8, 7, 6])

In [261]:
np.random.randint(0,10,20)

array([1, 2, 6, 0, 7, 5, 7, 1, 0, 6, 0, 3, 8, 5, 6, 5, 6, 5, 8, 4])

# How to sum a small array faster than np.sum? 


In [264]:
data=[1,5,9,3,0]
total=sum(data)
print(total)

18


# Consider two random array A and B, check if they are equal 


In [269]:
c=np.random.randint(0,100,(5,5))
f=np.random.randint(0,100,(5,5))
np.array_equiv(c,f)


False

# Make an array immutable (read-only) 

# Consider a random 5x2 matrix representing cartesian coordinates, convert them to polar coordinates 

In [293]:
import numpy as np
cart_matrix = np.random.rand(5,2)
r = np.sqrt(cart_matrix[:,0]**2 + cart_matrix[:,1]**2)
theta = np.arctan2(cart_matrix[:,1], cart_matrix[:,0])
print("Cartesian matrix:")
print(cart_matrix)
print("Polar coordinates:")
print(np.column_stack((r,theta)))


Cartesian matrix:
[[0.97664085 0.3272927 ]
 [0.4646949  0.4646127 ]
 [0.86873552 0.18590711]
 [0.32734895 0.57120844]
 [0.85778655 0.26273761]]
Polar coordinates:
[[1.03002323 0.32335844]
 [0.65711971 0.78530971]
 [0.88840467 0.21081763]
 [0.65835889 1.0504051 ]
 [0.89712252 0.29722398]]


# Create random vector of size 20 and replace the maximum value by 0 


In [278]:
sra=np.random.randint(1,10,20)
sra

array([8, 3, 3, 7, 3, 6, 6, 8, 3, 7, 5, 2, 3, 3, 8, 9, 4, 6, 7, 3])

In [296]:
import numpy as np
sra= np.random.rand(20)
max_index = np.argmax(sra)
sra[max_index] = 0
print(sra)

[0.3122617  0.59730787 0.         0.61127197 0.69804926 0.15476078
 0.5272056  0.05435281 0.20456256 0.36612526 0.48570725 0.23686055
 0.28955126 0.62179099 0.30840664 0.11288664 0.78894198 0.72773664
 0.71950508 0.50111817]


# Print the minimum and maximum representable value for each numpy scalar type 

In [309]:
import numpy as np

# How to print all the values of an array? 


In [314]:
my_array = [1, 2, 3, 4, 5]

for i in range(len(my_array)):
    print(my_array[i])

1
2
3
4
5


In [280]:
np.random.randint(0,10,(5,2)).ravel()



array([8, 1, 2, 0, 7, 2, 5, 8, 7, 2])

# How to convert a float (32 bits) array into an integer (32 bits) in place

In [315]:
import struct

float_array = [1.23, 2.34, 3.45, 4.56, 5.67]

for i in range(len(float_array)):
    int_value = struct.unpack('i', struct.pack('f', float_array[i]))[0]
    float_array[i] = struct.unpack('f', struct.pack('i', int_value))[0]
    print(int_value)

1067282596
1075167887
1079823565
1083304837
1085632676


# How to randomly place p elements in a 2D array? 

In [322]:
import numpy as np
import random


In [323]:
n_rows = 5
n_cols = 5
p = 5

In [324]:
array_2d = [[0 for i in range(n_cols)] for j in range(n_rows)]

In [325]:
for k in range(p):
    i = random.randint(0, n_rows - 1)
    j = random.randint(0, n_cols - 1)
    array_2d[i][j] = random.randint(1, 10)

In [326]:
for i in range(n_rows):
    for j in range(n_cols):
        print(array_2d[i][j], end=' ')
    print()

0 0 0 7 1 
0 0 0 0 0 
0 0 6 0 0 
0 0 10 0 0 
0 0 0 1 0 


In [328]:
import random
n_rows = 5
n_cols = 5
p = 5
array_2d = [[0 for i in range(n_cols)] for j in range(n_rows)]
for k in range(p):
    i = random.randint(0, n_rows - 1)
    j = random.randint(0, n_cols - 1)
    array_2d[i][j] = random.randint(1, 10)
for i in range(n_rows):
    for j in range(n_cols):
        print(array_2d[i][j], end=' ')
    print()

9 0 0 0 0 
0 0 0 0 0 
9 0 0 0 6 
9 0 0 0 0 
0 0 1 0 0 


# Subtract the mean of each row of a matrix 


In [329]:
x=np.random.randint(0,20,(5,5))

In [330]:
x

array([[10, 13,  3, 19,  7],
       [16, 16, 19, 15,  4],
       [12, 18,  2,  9, 11],
       [ 6, 12,  0, 11,  6],
       [19, 14, 19, 19,  1]])

In [331]:
y=np.mean(x)
y
x-y


array([[ -1.24,   1.76,  -8.24,   7.76,  -4.24],
       [  4.76,   4.76,   7.76,   3.76,  -7.24],
       [  0.76,   6.76,  -9.24,  -2.24,  -0.24],
       [ -5.24,   0.76, -11.24,  -0.24,  -5.24],
       [  7.76,   2.76,   7.76,   7.76, -10.24]])

# How to sort an array by the nth column? 

In [332]:
x=np.random.randint(0,20,(2,2))
x

array([[13,  9],
       [16, 18]])

In [333]:
x[:,::-1]

array([[ 9, 13],
       [18, 16]])

# How to tell if a given 2D array has null columns? 


In [334]:
x=np.random.randint(0,10,(5,5))
if 0 in x:
    print("null array")

null array


# Considering a four dimensions array, how to get sum over the last two axis at once? 

In [335]:
x=np.random.randint(0,10,(5,2))
x


array([[1, 2],
       [5, 8],
       [1, 2],
       [0, 1],
       [1, 5]])

In [336]:
x[-2:].sum()

7

# How to get the diagonal of a dot product? 

In [289]:

x=np.random.randint(0,20,(5,4))
y=np.random.randint(0,20,(4,3))

In [290]:
x

array([[ 9,  1, 16,  2],
       [ 8,  2, 19, 11],
       [16, 18,  1,  8],
       [ 0, 17, 17,  3],
       [11,  2,  6, 10]])

In [291]:
y

array([[12, 16,  0],
       [ 0,  3, 16],
       [14,  6, 15],
       [11, 11, 17]])

In [292]:
np.diag(np.dot(x,y))

array([354, 369, 439])

# Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? 

In [ ]:
import numpy as np


In [361]:
original_vector = [1, 2, 3, 4, 5]


In [362]:
new_vector = [val for val in original_vector for _ in range(4)][:-3]


In [363]:
print(new_vector)

[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5]


# Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? 

In [349]:
import numpy as np

In [350]:
arr_3d = np.random.rand(5,5,3)


In [351]:
arr_2d = np.random.rand(5,5)


In [352]:
result = arr_3d * arr_2d[:,:,np.newaxis]


In [353]:
print(result.shape) 

(5, 5, 3)


# How to swap two rows of an array? 


In [344]:
import numpy as np


In [345]:
sra = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])


In [346]:
sra[[0,1]] = sra[[1,0]]


In [347]:
print(sra)

[[4 5 6]
 [1 2 3]
 [7 8 9]]


# Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? 

In [340]:
Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
R = [Z[i:i+4] for i in range(len(Z)-3)]

In [342]:
print(R)

[[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8], [6, 7, 8, 9], [7, 8, 9, 10], [8, 9, 10, 11], [9, 10, 11, 12], [10, 11, 12, 13], [11, 12, 13, 14]]


In [343]:
R


[[1, 2, 3, 4],
 [2, 3, 4, 5],
 [3, 4, 5, 6],
 [4, 5, 6, 7],
 [5, 6, 7, 8],
 [6, 7, 8, 9],
 [7, 8, 9, 10],
 [8, 9, 10, 11],
 [9, 10, 11, 12],
 [10, 11, 12, 13],
 [11, 12, 13, 14]]

# Compute a matrix rank 

In [338]:
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]

# How to find the most frequent value in an array?


In [227]:
sra=np.array([2,3,4,5,2,1,6,7,8,2,2])

In [228]:
counts=np.bincount(sra)

In [231]:
most_frequent_value = np.argmax(counts)


In [232]:
print(most_frequent_value)

2


# How to get the n largest values of an array 

In [ ]:
To get the n largest values of a NumPy array, you can use the np.sort() and array[-n:] 

In [217]:
p=np.array([9,4,8,1,3])


In [220]:
n_largest=np.sort(p)[-2:]

In [221]:
print(n_largest)

[8 9]
